project_id = "hmrzmafwvhifjhsoizil"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]  
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:54324"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcnptYWZ3dmhpZmpoc29pemlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTg0NDgsImV4cCI6MjA1MzM3NDQ0OH0.GxaTSbm_f0R85dRMshUboGQioj5wgzA2h06FDbAzvh8"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcnptYWZ3dmhpZmpoc29pemlsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNzc5ODQ0OCwiZXhwIjoyMDUzMzc0NDQ4fQ.TJUlOUz0sXV_EMQp7JOF0-2S8mB3V8xDFnFAJMHYPyI"

[functions.generate-content]
verify_jwt = true

[functions.keyword-research]
verify_jwt = true

[functions.cms-integration]
verify_jwt = false

[functions.generate-images]  
verify_jwt = true

[functions.send-verification]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = true

[functions.generate-verification-token]
verify_jwt = true

[functions.verify-email-token]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.wp-config]
verify_jwt = true

[functions.wp-start-connect]
verify_jwt = true

[functions.wp-oauth-callback]
verify_jwt = false

[functions.send-email-with-config]
verify_jwt = true

[functions.update-email-config]
verify_jwt = true

[functions.twitter-connect]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.generate-prompt]
verify_jwt = true

[functions.daily-generation]
verify_jwt = false

[functions.shopify-oauth-start]
verify_jwt = false

[functions.shopify-oauth-callback]
verify_jwt = false

[functions.wix-oauth-start]
verify_jwt = false

[functions.wix-oauth-callback]
verify_jwt = false

[functions.wix-oauth-dbg]
verify_jwt = false

[functions.shopify-health]
verify_jwt = true

[functions.diag-logs]
verify_jwt = true

[functions.diag-health-shopify]
verify_jwt = true

[functions.diag-health-wix]
verify_jwt = true

[functions.diag-test-publish]
verify_jwt = true

[functions.integration-status]
verify_jwt = true

[functions.ping]
verify_jwt = false

[functions.wix-blog-publish]
verify_jwt = false

[functions.wix-connection-status]
verify_jwt = false

[functions.wix-site-info]
verify_jwt = false